export CPLUS_INCLUDE_PATH=../include
export CPPFLAGS=-O1
export LDFLAGS=-lpthread
export LIBRARY_PATH=./
targets=adapter array inserter list map remove_if reverse_iter set test vector mem_func cWrapper

all:$(targets)
#	for t in $(targets);\
#	do\
#		g++ -o $$t $$t.cpp;\
#	done

.PHONY: clean
clean:
	rm $(targets)
#adapter.cpp
#array.cpp
#inserter.cpp
#list.cpp
#map.cpp
#remove_if.cpp
#reverse_iter.cpp
#set.cpp
#test.cpp
#vector.cpp
