#!/usr/bin/python

cflags="-g -std=c++0x"
include_dir = [ '/home/dyc/github/program/netlib/net_client',
                '/home/dyc/github/program/netlib/net_client/utils',
                '/home/dyc/github/program/netlib/net_client/tools',
                '/home/dyc/tools/zlib/include', 
                '/home/dyc/tools/log4c/include', 
                '/home/dyc/github/program/common', 
                '/home/dyc/github/program/common/thread', 
                '/home/dyc/github/program/common/utils']

lib_dir = ['.', 
            "/home/dyc/github/program/common", 
            "/home/dyc/github/program/netlib/net_client", 
            "/home/dyc/tools/zlib/lib", 
            "/home/dyc/tools/log4c/lib"
            ]

env = Environment(CPPPATH = include_dir, CCFLAGS = cflags, tools=['default', 'packaging'])

deplibs=["common", "pthread", "z", "log4c", "netlib"]

env.Program('process_stat.cpp', 
        LIBPATH=lib_dir,
        LIBS=deplibs)
