#!/usr/bin/python

import os
import getpass

homedir = os.path.expanduser("~")

cflags="-g -std=c++0x"
include_dir = [ homedir + '/github/netlib/',
                homedir + '/github/netlib/utils',
                homedir + '/github/netlib/tools',
                homedir + '/tools/zlib/include', 
                homedir + '/tools/log4c/include', 
                homedir + '/github/program/common', 
                homedir + '/github/program/common/thread']

lib_dir = ['.', 
            homedir + "/github/program/common", 
            homedir + "/github//netlib/", 
            homedir + "/tools/zlib/lib", 
            homedir + "/tools/log4c/lib"
            ]

env = Environment(CPPPATH = include_dir, CCFLAGS = cflags, tools=['default', 'packaging'])

deplibs=["common", "pthread", "z", "log4c", "netlib"]

env.Program('process_stat.cpp', 
        LIBPATH=lib_dir,
        LIBS=deplibs)
