#!/usr/bin/python

env = Environment()
deplibs=["common", "pthread", "log4c"]

include_dir = [ '.', '/home/dyc/tools/log4c/include', 
                '/home/dyc/github/program/common', 
                '/home/dyc/github/program/common/thread', 
                '/home/dyc/github/program/common/utils']

lib_dir = ['.', "/home/dyc/github/program/common",
        "/home/dyc/tools/log4c/lib/"]

env.Program('partitioner.cpp', 
        CPPPATH = [include_dir],
        LIBPATH=lib_dir,
        LIBS=deplibs)

env = Environment(tools=['default', 'packaging'])
env.Install(install='/home/ding/test/bin/', source='partioner')

#env.Package( NAME           = 'foo',
#        VERSION        = '1.2.3',
#        PACKAGEVERSION = 0,
#        PACKAGETYPE    = 'rpm',
#        LICENSE        = 'gpl',
#        SUMMARY        = 'balalalalal',
#        DESCRIPTION    = 'this should be really really long',
#        X_RPM_GROUP    = 'Application/fu',
#        )


