#!/usr/bin/python

include_dir = [ '/home/dyc/github/program/netlib/net_client',
                '/home/dyc/github/program/netlib/net_client/utils',
                '/home/dyc/github/program/netlib/net_client/tools',
                '/home/dyc/tools/zlib/include', 
                '/home/dyc/tools/log4c/include', 
                '/home/dyc/github/program/common', 
                '/home/dyc/github/program/common/thread', 
                '/home/dyc/github/program/common/utils']

lib_dir = ['.', 
            "/home/dyc/github/program/common", 
            "/home/dyc/github/program/netlib/net_client", 
            "/home/dyc/tools/zlib/lib", 
            "/home/dyc/tools/log4c/lib"
            ]

env = Environment(CPPPATH = ['.'])
deplibs=["common", "pthread", "log4c"]

env.Program('partitioner.cpp', 
        CPPPATH = include_dir,
        LIBPATH=lib_dir,
        LIBS=deplibs, 
        LINKFLAGS = "-lprofiler")

env = Environment(tools=['default', 'packaging'])
env.Install(install='/home/ding/test/bin/', source='partioner')

#env.Package( NAME           = 'foo',
#        VERSION        = '1.2.3',
#        PACKAGEVERSION = 0,
#        PACKAGETYPE    = 'rpm',
#        LICENSE        = 'gpl',
#        SUMMARY        = 'balalalalal',
#        DESCRIPTION    = 'this should be really really long',
#        X_RPM_GROUP    = 'Application/fu',
#        )


