#!/usr/bin/python

#cflags="-g -std=c++0x"
cflags="-g"
include_dir = [ '/home/dyc/github/program/netlib/net_client',
                '/home/dyc/github/program/netlib/net_client/utils',
                '/home/dyc/github/program/netlib/net_client/tools',
                '/home/dyc/tools/zlib/include', 
                '/home/dyc/tools/log4c/include', 
                '/home/dyc/github/program/common', 
                '/home/dyc/github/program/common/thread', 
                '/home/dyc/github/program/common/utils']

lib_dir = ['.', "/home/dyc/github/program/common", "/home/dyc/tools/zlib/lib"]

env = Environment(CPPPATH = include_dir, CCFLAGS = cflags, tools=['default', 'packaging'])

deplibs=["common", "pthread", "z"]

env.Program('zpipe.c', 
        LIBPATH=lib_dir,
        LIBS=deplibs)
env.Install(install='/home/dyc/bin/', source='zpipe')

env.Program('ztest.c', 
        LIBPATH=lib_dir,
        LIBS=deplibs)
